### ISSUE TITLE
Telegraph list missing domain?

### ISSUE THREAD

**Issue by phpsystems** [danielcuthbert/thescum#11]
www.telegraph.co.uk appears to be missing from the list.

**Comment by alexhaydock** [comment]
I tried to address this in #10 as there are quite a few domains that could be added, particularly for The Telegraph.

It looks like the current Telegraph list only blocks Telegraph phishing domains and not their legitimate domains which could have happened by accident when it was being worked on.

**Comment by danielcuthbert** [comment]
You are right, that was an omission fault, fixed. thanks
